USE [master]
GO

/****** Object:  Database [fudbalskiTurnir]    Script Date: 7.7.2023. 15:23:12 ******/
DROP DATABASE [fudbalskiTurnir]
GO

/****** Object:  Database [fudbalskiTurnir]    Script Date: 7.7.2023. 15:23:12 ******/
CREATE DATABASE [fudbalskiTurnir]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fudbalskiTurnir', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\fudbalskiTurnir.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'fudbalskiTurnir_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\fudbalskiTurnir_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [fudbalskiTurnir].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [fudbalskiTurnir] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET ARITHABORT OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [fudbalskiTurnir] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [fudbalskiTurnir] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET  DISABLE_BROKER 
GO

ALTER DATABASE [fudbalskiTurnir] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [fudbalskiTurnir] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET RECOVERY FULL 
GO

ALTER DATABASE [fudbalskiTurnir] SET  MULTI_USER 
GO

ALTER DATABASE [fudbalskiTurnir] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [fudbalskiTurnir] SET DB_CHAINING OFF 
GO

ALTER DATABASE [fudbalskiTurnir] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [fudbalskiTurnir] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [fudbalskiTurnir] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [fudbalskiTurnir] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [fudbalskiTurnir] SET QUERY_STORE = OFF
GO

ALTER DATABASE [fudbalskiTurnir] SET  READ_WRITE 
GO

